import {Model} from "./models.js";

let bonesList = [
    'Neck/Basihyoid',
    'Neck/C1_Atlas',
    'Neck/C2_Axis',
    'Neck/C3',
    'Neck/C4',
    'Neck/C5',
    'Neck/C6',
    'Neck/C7',
    'Neck/Ceratohyoid',
    'Neck/Epihyoid',
    'Neck/Stylohyoid',
    'Neck/Thyrohyoid',
    
    'Skull/Mandible',
    'Skull/Skull',
    
    'Spine/Anticlinical_Vertebra',
    'Spine/Lumbar_Vertebrae',
    'Spine/Thoracic_Vertebrae',

    'Pelvis_Tail/Caudal_Vertebrae',
    'Pelvis_Tail/Caudal_Vertebrae1',
    'Pelvis_Tail/Caudal_Vertebrae2',
    'Pelvis_Tail/Caudal_Vertebrae3',
    'Pelvis_Tail/Caudal_Vertebrae4',
    'Pelvis_Tail/Caudal_Vertebrae5',
    'Pelvis_Tail/Caudal_Vertebrae6',
    'Pelvis_Tail/Caudal_Vertebrae7',
    'Pelvis_Tail/Caudal_Vertebrae8',
    'Pelvis_Tail/Caudal_Vertebrae9',
    'Pelvis_Tail/Caudal_Vertebrae10',
    'Pelvis_Tail/Caudal_Vertebrae11',
    'Pelvis_Tail/Caudal_Vertebrae12',
    'Pelvis_Tail/Caudal_Vertebrae13',
    'Pelvis_Tail/Caudal_Vertebrae14',
    'Pelvis_Tail/Caudal_Vertebrae15',
    'Pelvis_Tail/Caudal_Vertebrae16',
    'Pelvis_Tail/Caudal_Vertebrae17',
    'Pelvis_Tail/Caudal_Vertebrae18',
    'Pelvis_Tail/Os_Coxae',
    'Pelvis_Tail/Sacrum',
    
    'Legs/Left_Back/Calcaneus',
    'Legs/Left_Back/Central_Tarsal',
    'Legs/Left_Back/Femur',
    'Legs/Left_Back/Fibula',
    'Legs/Left_Back/Distal_Phalanges',
    'Legs/Left_Back/Middle_Phalanges',
    'Legs/Left_Back/Proximal_Phalanges',
    'Legs/Left_Back/Proximal_Sesamoid',
    'Legs/Left_Back/Metatarsal_I',
    'Legs/Left_Back/Metatarsal_II',
    'Legs/Left_Back/Metatarsal_III',
    'Legs/Left_Back/Metatarsal_IV',
    'Legs/Left_Back/Metatarsal_V',
    'Legs/Left_Back/Patella',
    'Legs/Left_Back/Tarsal_I',
    'Legs/Left_Back/Tarsal_II',
    'Legs/Left_Back/Tarsal_III',
    'Legs/Left_Back/Tarsal_IV',
    'Legs/Left_Back/Tibia',
    'Legs/Left_Back/Trochlea',

    'Legs/Right_Back/Calcaneus',
    'Legs/Right_Back/Central_Tarsal',
    'Legs/Right_Back/Femur',
    'Legs/Right_Back/Fibula',
    'Legs/Right_Back/Distal_Phalanges',
    'Legs/Right_Back/Middle_Phalanges',
    'Legs/Right_Back/Proximal_Phalanges',
    'Legs/Right_Back/Proximal_Sesamoid',
    'Legs/Right_Back/Metatarsal_I',
    'Legs/Right_Back/Metatarsal_II',
    'Legs/Right_Back/Metatarsal_III',
    'Legs/Right_Back/Metatarsal_IV',
    'Legs/Right_Back/Metatarsal_V',
    'Legs/Right_Back/Patella',
    'Legs/Right_Back/Tarsal_I',
    'Legs/Right_Back/Tarsal_II',
    'Legs/Right_Back/Tarsal_III',
    'Legs/Right_Back/Tarsal_IV',
    'Legs/Right_Back/Tibia',
    'Legs/Right_Back/Trochlea',
    
    'Legs/Left_Front/Accessory_Carpal',
    'Legs/Left_Front/Distal_Carpal_I',
    'Legs/Left_Front/Distal_Carpal_II',
    'Legs/Left_Front/Distal_Carpal_III',
    'Legs/Left_Front/Distal_Carpal_IV',
    'Legs/Left_Front/Ulnar',
    'Legs/Left_Front/Ulna',
    'Legs/Left_Front/Distal_Phalanges',
    'Legs/Left_Front/Middle_Phalanges',
    'Legs/Left_Front/Proximal_Phalanges',
    'Legs/Left_Front/Proximal_Sesamoid',
    'Legs/Left_Front/Humerus',
    'Legs/Left_Front/Metacarpal_I',
    'Legs/Left_Front/Metacarpal_II',
    'Legs/Left_Front/Metacarpal_III',
    'Legs/Left_Front/Metacarpal_IV',
    'Legs/Left_Front/Metacarpal_V',
    'Legs/Left_Front/Radial',
    'Legs/Left_Front/Radius',
    'Legs/Left_Front/Scapula',

    'Legs/Right_Front/Accessory_Carpal',
    'Legs/Right_Front/Distal_Carpal_I',
    'Legs/Right_Front/Distal_Carpal_II',
    'Legs/Right_Front/Distal_Carpal_III',
    'Legs/Right_Front/Distal_Carpal_IV',
    'Legs/Right_Front/Ulnar',
    'Legs/Right_Front/Ulna',
    'Legs/Right_Front/Distal_Phalanges',
    'Legs/Right_Front/Middle_Phalanges',
    'Legs/Right_Front/Proximal_Phalanges',
    'Legs/Right_Front/Proximal_Sesamoid',
    'Legs/Right_Front/Humerus',
    'Legs/Right_Front/Metacarpal_I',
    'Legs/Right_Front/Metacarpal_II',
    'Legs/Right_Front/Metacarpal_III',
    'Legs/Right_Front/Metacarpal_IV',
    'Legs/Right_Front/Metacarpal_V',
    'Legs/Right_Front/Radial',
    'Legs/Right_Front/Radius',
    'Legs/Right_Front/Scapula',

    'Ribs/Ribs',
    'Ribs/Sternebrae',
    'Ribs/Xiphoid_Process',
    
    'Organs/Bladder',
    'Organs/Duodenom',
    'Organs/Heart',
    'Organs/Kidneys',
    'Organs/Large_Intestine',
    'Organs/Liver',
    'Organs/Lungs',
    'Organs/Small_Intestine',
    'Organs/Spleen',
    'Organs/Stomach',
    'Organs/Renal_Artery',
    'Organs/Renal_Artery1',
    'Organs/Renal_Vein',
    'Organs/Renal_Vein1',
    'Organs/Ureter',
    'Organs/Ureter1',
    'Organs/Vena_Cava',
];

export default new Model(
    "Canine",
    bonesList,
    .032,
    [0, 8, 0],
    "This is a model of a Canine",
    "/img/models/preview/canine.png"
);