import {Model} from "./models.js";

let bonesList = [ 
    'Neck/Cervical_Vertebrae',
    'Neck/Cervical_Vertebrae1',
    'Neck/Cervical_Vertebrae2',
    'Neck/Cervical_Vertebrae3',
    'Neck/Cervical_Vertebrae4',
    'Neck/Cervical_Vertebrae5',
    'Neck/Cervical_Vertebrae6',

    'Skull/Cranium',

    'Skull/Mandible',
    
    'Skull/Nasal_Septum',
    
    'Skull/Ethmoid_Turbinates',

    'Spine/Lumbar_Vertebrae',
    'Spine/Lumbar_Vertebrae1',
    'Spine/Lumbar_Vertebrae2',
    'Spine/Lumbar_Vertebrae3',
    'Spine/Lumbar_Vertebrae4',
    'Spine/Lumbar_Vertebrae5',

    'Spine/Thoracic_Vertebrae',
    'Spine/Thoracic_Vertebrae1',
    'Spine/Thoracic_Vertebrae2',
    'Spine/Thoracic_Vertebrae3',
    'Spine/Thoracic_Vertebrae4',
    'Spine/Thoracic_Vertebrae5',
    'Spine/Thoracic_Vertebrae6',
    'Spine/Thoracic_Vertebrae7',
    'Spine/Thoracic_Vertebrae8',
    'Spine/Thoracic_Vertebrae9',
    'Spine/Thoracic_Vertebrae10',
    'Spine/Thoracic_Vertebrae11',
    'Spine/Thoracic_Vertebrae12',
    'Spine/Thoracic_Vertebrae13',
    'Spine/Thoracic_Vertebrae14',
    'Spine/Thoracic_Vertebrae15',
    'Spine/Thoracic_Vertebrae16',
    'Spine/Thoracic_Vertebrae17',

    'Teeth/Lower_Canine',
    'Teeth/Lower_Canine1',
    'Teeth/Lower_Incisor',
    'Teeth/Lower_Incisor1',
    'Teeth/Lower_Incisor2',
    'Teeth/Lower_Incisor3',
    'Teeth/Lower_Incisor4',
    'Teeth/Lower_Incisor5',

    'Teeth/Mandibular_Molar',
    'Teeth/Mandibular_Molar1',
    'Teeth/Mandibular_Molar2',
    'Teeth/Mandibular_Molar3',
    'Teeth/Mandibular_Molar4',
    'Teeth/Mandibular_Molar5',
    
    'Teeth/Mandibular_Premolar',
    'Teeth/Mandibular_Premolar1',
    'Teeth/Mandibular_Premolar2',
    'Teeth/Mandibular_Premolar3',
    'Teeth/Mandibular_Premolar4',
    'Teeth/Mandibular_Premolar5',
    
    'Teeth/Maxilary_Molar',
    'Teeth/Maxilary_Molar1',
    'Teeth/Maxilary_Molar2',
    'Teeth/Maxilary_Molar3',
    'Teeth/Maxilary_Molar4',
    'Teeth/Maxilary_Molar5',
    
    'Teeth/Maxilary_Premolar',
    'Teeth/Maxilary_Premolar1',
    'Teeth/Maxilary_Premolar2',
    'Teeth/Maxilary_Premolar3',
    'Teeth/Maxilary_Premolar4',
    'Teeth/Maxilary_Premolar5',
    
    'Teeth/Upper_Canine',
    'Teeth/Upper_Canine1',
    
    'Teeth/Upper_Incisor',
    'Teeth/Upper_Incisor1',
    'Teeth/Upper_Incisor2',
    'Teeth/Upper_Incisor3',
    'Teeth/Upper_Incisor4',
    'Teeth/Upper_Incisor5',
    
    'Pelvis_Tail/Caudal_Vertebrae',
    'Pelvis_Tail/Caudal_Vertebrae1',
    'Pelvis_Tail/Caudal_Vertebrae2',
    'Pelvis_Tail/Caudal_Vertebrae3',
    'Pelvis_Tail/Caudal_Vertebrae4',
    'Pelvis_Tail/Caudal_Vertebrae5',
    'Pelvis_Tail/Caudal_Vertebrae6',
    'Pelvis_Tail/Pelvis',
    'Pelvis_Tail/Sacral_Vertebrae',

    'Legs/Left_Back/Calcaneus',
    'Legs/Left_Back/Cannon',
    'Legs/Left_Back/Central_Tarsal',
    'Legs/Left_Back/Coffin',
    'Legs/Left_Back/Femur',
    'Legs/Left_Back/Fibula',
    'Legs/Left_Back/Fourth_Tarsal',
    'Legs/Left_Back/Long_Pastern',
    'Legs/Left_Back/Navicular',
    'Legs/Left_Back/Patella',
    'Legs/Left_Back/Sesamoids',
    'Legs/Left_Back/Short_Pastern',
    'Legs/Left_Back/Splint_Fourth_Metatarsal',
    'Legs/Left_Back/Splint_Second_Metatarsal',
    'Legs/Left_Back/Talus',
    'Legs/Left_Back/Third_Tarsal',
    'Legs/Left_Back/Tibia',
    
    'Legs/Right_Back/Calcaneus',
    'Legs/Right_Back/Cannon',
    'Legs/Right_Back/Central_Tarsal',
    'Legs/Right_Back/Coffin',
    'Legs/Right_Back/Femur',
    'Legs/Right_Back/Fibula',
    'Legs/Right_Back/Fourth_Tarsal',
    'Legs/Right_Back/Long_Pastern',
    'Legs/Right_Back/Navicular',
    'Legs/Right_Back/Patella',
    'Legs/Right_Back/Sesamoids',
    'Legs/Right_Back/Short_Pastern',
    'Legs/Right_Back/Splint_Fourth_Metatarsal',
    'Legs/Right_Back/Splint_Second_Metatarsal',
    'Legs/Right_Back/Talus',
    'Legs/Right_Back/Third_Tarsal',
    'Legs/Right_Back/Tibia',

    'Legs/Left_Front/Cannon',
    'Legs/Left_Front/Coffin',
    'Legs/Left_Front/Fourth_Carpal',
    'Legs/Left_Front/Humerus',
    'Legs/Left_Front/Intermediate_Carpal',
    'Legs/Left_Front/Long_Pastern',
    'Legs/Left_Front/Navicular',
    'Legs/Left_Front/Radial_Carpal',
    'Legs/Left_Front/Radius',
    'Legs/Left_Front/Scapula',
    'Legs/Left_Front/Second_Carpal',
    'Legs/Left_Front/Sesamoids',
    'Legs/Left_Front/Short_Pastern',
    'Legs/Left_Front/Splints',
    'Legs/Left_Front/Third_Carpal',
    'Legs/Left_Front/Ulnar_Accessory_Carpal',

    'Legs/Right_Front/Cannon',
    'Legs/Right_Front/Coffin',
    'Legs/Right_Front/Fourth_Carpal',
    'Legs/Right_Front/Humerus',
    'Legs/Right_Front/Intermediate_Carpal',
    'Legs/Right_Front/Long_Pastern',
    'Legs/Right_Front/Navicular',
    'Legs/Right_Front/Radial_Carpal',
    'Legs/Right_Front/Radius',
    'Legs/Right_Front/Scapula',
    'Legs/Right_Front/Second_Carpal',
    'Legs/Right_Front/Sesamoids',
    'Legs/Right_Front/Short_Pastern',
    'Legs/Right_Front/Splints',
    'Legs/Right_Front/Third_Carpal',
    'Legs/Right_Front/Ulnar_Accessory_Carpal',

    'Ribs/Rib_Cartilage',
    'Ribs/Rib_Cartilage1',
    'Ribs/Rib_Cartilage2',
    'Ribs/Ribs',
    'Ribs/Sternum',
    
    'Cavities/Dorsal_Nasal_Concha',
    'Cavities/Ventral_Nasal_Concha',
    
    'Organs/Brain',
    'Organs/Eyes',
    'Organs/Gutteral_Pouches',        
    
    'Muscles/Cranial_Muscles/Auricular 2',
    'Muscles/Cranial_Muscles/Auricular',
    'Muscles/Cranial_Muscles/Buccinator',
    'Muscles/Cranial_Muscles/Levator Annuli Oris Fascialis',
    'Muscles/Cranial_Muscles/Levator Labii',
    'Muscles/Cranial_Muscles/Levator Nasolabialis',
    'Muscles/Cranial_Muscles/Masseter',
    'Muscles/Cranial_Muscles/Orbicularis Occuli',
    'Muscles/Cranial_Muscles/Orbicularis',
    'Muscles/Cranial_Muscles/Orbital Muscles',
    'Muscles/Cranial_Muscles/Temporal 2',
    'Muscles/Cranial_Muscles/Temporal',
    'Muscles/Cranial_Muscles/Zygomaticus 2',
    'Muscles/Cranial_Muscles/Zygomaticus',

    'Muscles/Soft_Palate',
    'Muscles/Tongue',

    'Muscles/Leg_Muscles/Right_Front/Bicep_Brachii',
    'Muscles/Leg_Muscles/Right_Front/Common_Digital_Extensor',
    'Muscles/Leg_Muscles/Right_Front/Deltoid',
    'Muscles/Leg_Muscles/Right_Front/Extensor_Carpi_Radialis',
    'Muscles/Leg_Muscles/Right_Front/Flexor_Carpi_Radialis',
    'Muscles/Leg_Muscles/Right_Front/Flexor_Carpi_Ulnaris',
    'Muscles/Leg_Muscles/Right_Front/splenius',
    'Muscles/Leg_Muscles/Right_Front/Superficial_Digital_Flexor',
    'Muscles/Leg_Muscles/Right_Front/Supraspinatus',
    'Muscles/Leg_Muscles/Right_Front/Trapezius',
    'Muscles/Leg_Muscles/Right_Front/Tricep',
    'Muscles/Leg_Muscles/Right_Front/Tricep_2',
    
    'Cartilage/Ears',
    'Cartilage/Laryngeal_Cartilages_Arytenoids',
    'Cartilage/Laryngeal_Cartilages_Circoid',
    'Cartilage/Laryngeal_Cartilages_Epiglottis',
    'Cartilage/Laryngeal_Cartilages_Thyroid',
    'Cartilage/Nares',

    'Vascular_System/Legs/Right_Front/Arteries',
    'Vascular_System/Legs/Right_Front/Veins',


    'Nervous_System/Leg_Nerves/Right_Front/Nerves',

    'Nervous_System/Cranial_Nerves/CN I - Olfactory Nerve',
    'Nervous_System/Cranial_Nerves/CN II - Optic Nerve',
    'Nervous_System/Cranial_Nerves/CN III - Oculomotor Nerve',
    'Nervous_System/Cranial_Nerves/CN IV - Trochlear Nerve',
    'Nervous_System/Cranial_Nerves/CN IX - Glossopharyngeal Nerve',
    'Nervous_System/Cranial_Nerves/CN V - Trigeminal Nerve',
    'Nervous_System/Cranial_Nerves/CN VI - Abducens Nerve',
    'Nervous_System/Cranial_Nerves/CN VII - Facial Nerve',
    'Nervous_System/Cranial_Nerves/CN VIII - Vestibulocochlear Nerve',
    'Nervous_System/Cranial_Nerves/CN X - Vagus nerve',
    'Nervous_System/Cranial_Nerves/CN XI - Accessory Nerve',
    'Nervous_System/Cranial_Nerves/CN XII - Hypoglossal Nerve'



    
    ];

export default new Model(
    "Equine",
    bonesList,
    11,
    [0, 10, -1],
    "Equine Model",
    "/img/models/preview/equine.png"
);