name: Sync Development branch to docker-prod hosting (https://anatomy.viz.lib.vt.edu/dev/)

on:
  push:
    branches:
    - Development

jobs:
  deploy:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - run: |
        cp -ru $GITHUB_WORKSPACE/. /public_html/dev
        rm -rf /public_html/dev/.git*
