name: Sync Development branch to docker-prod hosting

on:
  push:
    branches:
    - Development

jobs:
  deploy:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - run: |
        echo $GITHUB_WORKSPACE
        ls -al $GITHUB_WORKSPACE
        cp -ru $GITHUB_WORKSPACE/ /public_html/dev
        rm -rf /public_html/dev/.git*
